### ISSUE TITLE
No IOS target, No Android build

### ISSUE THREAD

**Issue by stephane-wis** [jamcneil/XamarinFormsCSS#1]
Hi, I tried to run the Android and got an error about Mono and NuGet, and I wasn't able to build the iOS target because some (unknown) settings was set to 'do not build'. Could you please verify?

**Comment by jamcneil** [comment]
Absolutely.  I will look at it when I get to a computer on Monday.  Thanks for letting me know.

Sent from my iPhone

On Sep 23, 2018, at 5:56 AM, stephane-wis <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I tried to run the Android and got an error about Mono and NuGet, and I wasn't able to build the iOS target because some (unknown) settings was set to 'do not build'. Could you please verify?

**Comment by jamcneil** [comment]
I verified that all is working as expected. If you would like help checking your setup, email me at judy.mcneil@microsoft.com with the specific errors and I will see if I can help there.
